{% set name = "jupyterlab-accessible-themes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3856038442e8455a86b4d42784bf11eebaddebfff2ac78a98e3f42de0e2b618f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - nodejs
    - yarn
    - python >=3.6
    - pip
    - jupyterlab <4
    - jupyter-packaging
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Quansight-Labs/jupyterlab-accessible-themes
  summary: 'accessible jupyter lab themes'
  description: |
    this project defines a set of accessible themes according to WCAG color
    standards. Please note that some themes are optimized for colorblindness
    and/or high contrast. Inside the readme of each theme you will find
    detailed information of the colors, its purpose and reference links from
    the original authors.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/Quansight-Labs/jupyterlab-accessible-themes
  dev_url: https://github.com/Quansight-Labs/jupyterlab-accessible-themes

extra:
  recipe-maintainers:
    - steff456
    - trallard
    - gabalafou
